### ISSUE TITLE
error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ and ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’)      cloud = std::make_shared<PointCloud>();

### ISSUE THREAD

**Issue by HouZhe1** [lturing/ORB_SLAM3_ROS#1]
![{B5E SE29C4U _VQZ7@TG](https://user-images.githubusercontent.com/97662267/231421464-c9d384a1-aa51-413f-ab7b-1bb139acd9c9.png)
请问我在build.sh时最后编译PointCloudMapping.cc时报了这个错误，我用的PCL是1.8.1版本的

**Comment by HouZhe1** [comment]
在cloud前面加一个 auto就可以了
auto cloud = std::make_shared<PointCloud>;

**Comment by StevenLiuMC** [comment]
> 在cloud前面加一个 auto就可以了 auto cloud = std::make_shared;

有用好用，非常好评
