### ISSUE TITLE
如何保存点云地图

### ISSUE THREAD

**Issue by 1803170327** [lturing/ORB_SLAM3_ROS#10]
我使用自制的TUM数据集成功运行了程序，并且在rviz界面可以查看到生成的点云地图。但是我不知道在哪保存生成的点云，百度到的方法是修改/src/MapDrawer.cc文件，我尝试修改后重新编译工程依然没有保存地图。
百度到的方法如下：https://blog.csdn.net/Aer_7z/article/details/132645349

**Comment by 1803170327** [comment]
我看rviz界面是通过订阅点云的topic来实现点云可视化，那或许可以通过订阅点云的topic来保存地图？请问这样是可行的吗？

**Comment by lturing** [comment]
可以用KeyFrameTrajectory.txt、输入图像、深度图恢复点云

**Comment by qinqi-mm** [comment]
> 我看rviz界面是通过订阅点云的topic来实现点云可视化，那或许可以通过订阅点云的topic来保存地图？请问这样是可行的吗？

您好，冒昧地请问一下您有实现点云地图地保存了吗

**Comment by 1803170327** [comment]
> > 我看rviz界面是通过订阅点云的topic来实现点云可视化，那或许可以通过订阅点云的topic来保存地图？请问这样是可行的吗？
> 
> 您好，冒昧地请问一下您有实现点云地图地保存了吗

已经实现了，我修改了部分的代码，修改如下：
打开/src/SlamDataPub.cc
在头文件引用加入：
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/io/pcd_io.h>

在SlamDataPub：：CloudPointMappingPub()函数if语句最后添加：
pcl::io::savePCDFileBinary(“/home/maxwell/Desktop/map.pcd”,*globalCloud);
<img width="415" alt="image" src="https://github.com/user-attachments/assets/400b68ba-f44e-4fb9-b3ea-e58b086085e5">

修改完成之后重新编译工程即可。

这种存储方式就是每当生成一份global pointcloud就存储一次，每次存储的文件名不变，后来者就会覆盖上一次的结果，只能说是能用，更好的存储方式我没有去寻找了。

**Comment by qinqi-mm** [comment]
> > > 我看rviz界面是通过订阅点云的topic来实现点云可视化，那或许可以通过订阅点云的topic来保存地图？请问这样是可行的吗？
> > 
> > 
> > 您好，冒昧地请问一下您有实现点云地图地保存了吗
> 
> 已经实现了，我修改了部分的代码，修改如下： 打开/src/SlamDataPub.cc 在头文件引用加入： #include <pcl/point_types.h> #include <pcl/point_cloud.h> #include <pcl/io/pcd_io.h>
> 
> 在SlamDataPub：：CloudPointMappingPub()函数if语句最后添加： pcl::io::savePCDFileBinary(“/home/maxwell/Desktop/map.pcd”,*globalCloud); <img alt="image" width="415" src="https://private-user-images.githubusercontent.com/115651829/353649540-400b68ba-f44e-4fb9-b3ea-e58b086085e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTc5MDUsIm5iZiI6MTcyMjk1NzYwNSwicGF0aCI6Ii8xMTU2NTE4MjkvMzUzNjQ5NTQwLTQwMGI2OGJhLWY0NGUtNGZiOS1iM2VhLWU1OGIwODYwODVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjczYjQxNDYyZmVhOTc2YmMwODY1MjUzYzY0ODk2NjY5MjVlYjk3MzVjZmQ0ZDUxZmMzZmE2MmZhNzYwMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EsZxq-Ba4ug7TpPqcyTx3J4u32j-e1bzTTygnXU6-C4">
> 
> 修改完成之后重新编译工程即可。
> 
> 这种存储方式就是每当生成一份global pointcloud就存储一次，每次存储的文件名不变，后来者就会覆盖上一次的结果，只能说是能用，更好的存储方式我没有去寻找了。

太感谢您了！我之前试着在if的开头加，但是运行结束没有生成pcd文件，按照您的方法可以成功获得，十分感谢您的回复！

**Comment by 1803170327** [comment]
> > > > 我看rviz界面是通过订阅点云的topic来实现点云可视化，那或许可以通过订阅点云的topic来保存地图？请问这样是可行的吗？
> > > 
> > > 
> > > 您好，冒昧地请问一下您有实现点云地图地保存了吗
> > 
> > 
> > 已经实现了，我修改了部分的代码，修改如下： 打开/src/SlamDataPub.cc 在头文件引用加入： #include <pcl/point_types.h> #include <pcl/point_cloud.h> #include <pcl/io/pcd_io.h>
> > 在SlamDataPub：：CloudPointMappingPub()函数if语句最后添加： pcl::io::savePCDFileBinary(“/home/maxwell/Desktop/map.pcd”,*globalCloud); <img alt="image" width="415" src="https://private-user-images.githubusercontent.com/115651829/353649540-400b68ba-f44e-4fb9-b3ea-e58b086085e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTc5MDUsIm5iZiI6MTcyMjk1NzYwNSwicGF0aCI6Ii8xMTU2NTE4MjkvMzUzNjQ5NTQwLTQwMGI2OGJhLWY0NGUtNGZiOS1iM2VhLWU1OGIwODYwODVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjczYjQxNDYyZmVhOTc2YmMwODY1MjUzYzY0ODk2NjY5MjVlYjk3MzVjZmQ0ZDUxZmMzZmE2MmZhNzYwMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EsZxq-Ba4ug7TpPqcyTx3J4u32j-e1bzTTygnXU6-C4">
> > 修改完成之后重新编译工程即可。
> > 这种存储方式就是每当生成一份global pointcloud就存储一次，每次存储的文件名不变，后来者就会覆盖上一次的结果，只能说是能用，更好的存储方式我没有去寻找了。
> 
> 太感谢您了！我之前试着在if的开头加，但是运行结束没有生成pcd文件，按照您的方法可以成功获得，十分感谢您的回复！

![urwelcome](https://github.com/user-attachments/assets/7e7b9158-1f0a-4667-888e-f867bb929b1c)
