### ISSUE TITLE
Question: how to run my own rosbags using this repo to build a dense point cloud map in rgbd mode?

### ISSUE THREAD

**Issue by sirackerman** [lturing/ORB_SLAM3_ROS#11]
Hi @lturing , thanks for your works on this algorithms. I'd like to request guidance on how to generate the dense point cloud map using my own rosbag recorded with realsensed435i using your repo (if it's possible). Thanks in advance.

**Comment by lturing** [comment]
you can run tum rgbd dataset firstly, and organize your dataset as tum

**Comment by sirackerman** [comment]
Alright thank you
