### ISSUE TITLE
KeyFrameTrajectory.txt没有保存

### ISSUE THREAD

**Issue by XinCheng-lee** [lturing/ORB_SLAM3_ROS#12]
There are 1 cameras in the atlas
Camera 0 is pinhole
strSettingPath=/mnt2/lxc/ORB_SLAM3_ROS/Examples/RGB-D/RealSense_D455.yaml
First KF:0; Map init KF:0
New Map created with 748 points
[rviz-1] process has finished cleanly
log file: /mnt2/lxc/.ros/log/fe8a57fc-b058-11ef-b76f-b9a3ad99e199/rviz-1*.log

^C[orb_slam3-2] killing on exit
Shutdown

**Saving keyframe trajectory to KeyFrameTrajectory.txt ...**
shutting down processing monitor...
... shutting down processing monitor complete
done

CTRL + C关掉rviz后没有保存KeyFrameTrajectory.txt。

**Comment by lturing** [comment]
可以添加/stop/orbslam 的话题以及相关的callback函数，在callback函数中实现KeyFrameTrajectory.txt的保存以及终止程序

**Comment by XinCheng-lee** [comment]
我这里把KeyFrameTrajectory.txt改为具体的路径，就可以保存。

"KeyFrameTrajectory.txt" --> "/mnt2/lxc/ORB_SLAM3_ROS/KeyFrameTrajectory.txt"
SLAM.SaveTrajectoryEuRoC("/mnt2/lxc/ORB_SLAM3_ROS/KeyFrameTrajectory.txt");
