### ISSUE TITLE
下载数据集，直接运行报错

### ISSUE THREAD

**Issue by RaySaii** [lturing/ORB_SLAM3_ROS#3]
![image](https://github.com/lturing/ORB_SLAM3_ROS/assets/24506255/17e61694-3085-4d09-8503-be6c35488a54)
这是我的lanuch
![image](https://github.com/lturing/ORB_SLAM3_ROS/assets/24506255/c62dae1a-483d-4af2-97b5-e9f1279c18b0)
我的环境是windows下vm虚拟机，ubuntu 20.04. 分配了6核和8g内存

**Comment by easylife2567** [comment]
我也是同样的错误，求解

**Comment by lturing** [comment]
[line 2](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L2) 和 [line 4](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L4)间的是注释。这里没有用到bag，数据集直接下载图片等信息

**Comment by ghost** [comment]
> 我也是同样的错误，求解

我也是同样的问题，兄弟你解决了吗？

**Comment by ghost** [comment]
> ![image](https://private-user-images.githubusercontent.com/24506255/237649179-17e61694-3085-4d09-8503-be6c35488a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mzk3NDIsIm5iZiI6MTcxMjczOTQ0MiwicGF0aCI6Ii8yNDUwNjI1NS8yMzc2NDkxNzktMTdlNjE2OTQtMzA4NS00ZDA5LTg1MDMtYmU2YzM1NDg4YTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4NTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMDMyYWFlMDVjMzE4ZjQyZjQ1MjhkOWNhODcwYTMxMjNlMWEzMDk5NWEyMWIyOTI2ZTBkNmUyMjg5YTNmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZNX2uaDe_0YfC0PUib7Neh7ge6rJrCyQL8wuqCe8T8) 这是我的lanuch ![image](https://private-user-images.githubusercontent.com/24506255/237649334-c62dae1a-483d-4af2-97b5-e9f1279c18b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mzk3NDIsIm5iZiI6MTcxMjczOTQ0MiwicGF0aCI6Ii8yNDUwNjI1NS8yMzc2NDkzMzQtYzYyZGFlMWEtNDgzZC00YWYyLTk3YjUtZTlmMTI3OWMxOGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4NTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOWUzY2JlOTE5NjkwMTkyMDQ2ZTJiNjU1Y2QyZGMwYzU1N2ZjMzI2MzU4M2FlMDA0YzNkZWUzZTRjNDczZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PkBdmPchhxFxk3ybYz86NiJRn4aW207HULSDuqIZmYo) 我的环境是windows下vm虚拟机，ubuntu 20.04. 分配了6核和8g内存

我也是同样的问题，兄弟你解决了吗？

**Comment by easylife2567** [comment]
我当时是8g内存也不够，还得再大些

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月10日 16:58 |
| 收件人 | lturing/ORB_SLAM3_ROS ***@***.***> |
| 抄送人 | Void ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [lturing/ORB_SLAM3_ROS] 下载数据集，直接运行报错 (Issue #3) |

这是我的lanuch 我的环境是windows下vm虚拟机，ubuntu 20.04. 分配了6核和8g内存

我也是同样的问题，兄弟你解决了吗？
