### ISSUE TITLE
三维重建demo无效果

### ISSUE THREAD

**Issue by create-li** [lturing/ORB_SLAM3_ROS#4]
我复现三维重建dem
![2023-08-17 15-23-12 的屏幕截图](https://github.com/lturing/ORB_SLAM3_ROS/assets/9958979/640839b5-ddc6-4e6c-9aca-db7400ad8c0f)
o只有界面，没有其他显示。

我按照教程，修改的launth的数据集路径
`<launch>
    
    
   
    <node pkg="rviz" type="rviz" name="rviz" args="-d $(find orb_slam3)/rviz/orb_viz_rgbd_mapping.rviz" />

    <node pkg="orb_slam3" type="ros_rgbd_mapping" name="orb_slam3" args="$(find orb_slam3)/Examples/RGB-D/TUM1.yaml $(find orb_slam3)/Vocabulary/ORBvoc.txt /home/project/slam/dataset/rgbd_dataset_freiburg2_large_with_loop" output="screen" />

</launch>`
rgbd_dataset_freiburg2_large_with_loop 解压后的文件夹，解压后进行depth.txt 和rgb.txt 关联生成associations.txt
然后运行run_rgbd_mapping.sh 
没有报错，就是没有任何效果。
请问步骤是否正确，还需要什么操作吗？

**Comment by create-li** [comment]
我将数据集改成bag后，在左侧可以显示深度图片和rgb图，右边的没有任何效果、也没有任何点线显示

**Comment by lturing** [comment]
```
命令行有打印什么信息吗
<!-- xxx --> 是注释，这里没有用到bag
```
