### ISSUE TITLE
[orb_slam3-3] process has died [pid 17098, exit code -11

### ISSUE THREAD

**Issue by StevenLiuMC** [lturing/ORB_SLAM3_ROS#7]
作者您好，我试着在自己的虚拟机上编译了您的代码，虚拟机系统为ubuntu 20.04，内存分配为11G，在build.sh文件中默认的make -j8情况下我发现会出现因为内存不够而杀掉进程的情况，会产生fatal报错，改成make -j4可以了，然后我试着运行rgbd深度建图，结果会抛出以下异常：
[orb_slam3-3] process has died [pid 17098, exit code -11, cmd /home/liu/ORB_SLAM3_ROS/Examples/ROS/ros_rgbd_mapping /home/liu/ORB_SLAM3_ROS/Examples/RGB-D/TUM2.yaml /home/liu/ORB_SLAM3_ROS/Vocabulary/ORBvoc.txt /home/liu/Datasets/TUM/rgbd_dataset_freiburg1_room __name:=orb_slam3 __log:=/home/liu/.ros/log/31ed43ba-11d6-11ef-abaa-690a54b09ddf/orb_slam3-3.log].
log file: /home/liu/.ros/log/31ed43ba-11d6-11ef-abaa-690a54b09ddf/orb_slam3-3*.log
请问这种情况是否也和虚拟机内存不足算力不够有关呢？我怀疑是虚拟机的原因，因为rviz启动后有一下是能够收到数据集传来的图像的，但是紧接着进程被杀掉后就没有图像进一步传过来了。

**Comment by lturing** [comment]
可以调试看看报错信息
首先安装 sudo apt install stterm # 安装stterm

例如将[Line5](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L5)改为
```
<node pkg="rviz" type="rviz" name="rviz" args="-d $(find orb_slam3)/rviz/orb_viz_rgbd_mapping.rviz" />
改为：

<node pkg="rviz" type="rviz" name="rviz" args="-d $(find orb_slam3)/rviz/orb_viz_rgbd_mapping.rviz" output="log" launch-prefix="stterm -g 200x60 -e gdb -ex run --args"   />
```
以上是调试rviz这个节点。

以及将[line6](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L6)改为
```
<node pkg="orb_slam3" type="ros_rgbd_mapping" name="orb_slam3" args="$(find orb_slam3)/Examples/RGB-D/TUM2.yaml $(find orb_slam3)/Vocabulary/ORBvoc.txt /home/spurs/dataset/rgbd_dataset_freiburg2_large_with_loop" output="screen" />

改为：

<node pkg="orb_slam3" type="ros_rgbd_mapping" name="orb_slam3" args="$(find orb_slam3)/Examples/RGB-D/TUM2.yaml $(find orb_slam3)/Vocabulary/ORBvoc.txt /home/spurs/dataset/rgbd_dataset_freiburg2_large_with_loop" output="screen" output="log" launch-prefix="stterm -g 200x60 -e gdb -ex run --args" />

```
以上调试orb_slam3这个节点

**Comment by wfpurgator** [comment]
我也有同样的报错，原因是我把稠密建图的参数输入从argv改成param，在systerm.cc 
mpSlamDataPub = new SlamDataPub(this, mpFrameDrawer, mpMapDrawer, mpTracker, strSettingsFile, mpAtlas);  //zl
处直接报错退出了，没什么修改的头绪
@lturing

**Comment by StevenLiuMC** [comment]
> 可以调试看看报错信息 首先安装 sudo apt install stterm # 安装stterm
> 
> 例如将[Line5](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L5)改为
> 
> ```
> <node pkg="rviz" type="rviz" name="rviz" args="-d $(find orb_slam3)/rviz/orb_viz_rgbd_mapping.rviz" />
> 改为：
> 
> <node pkg="rviz" type="rviz" name="rviz" args="-d $(find orb_slam3)/rviz/orb_viz_rgbd_mapping.rviz" output="log" launch-prefix="stterm -g 200x60 -e gdb -ex run --args"   />
> ```
> 
> 以上是调试rviz这个节点。
> 
> 以及将[line6](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/launch/orb_slam_rgbd_mapping.launch#L6)改为
> 
> ```
> <node pkg="orb_slam3" type="ros_rgbd_mapping" name="orb_slam3" args="$(find orb_slam3)/Examples/RGB-D/TUM2.yaml $(find orb_slam3)/Vocabulary/ORBvoc.txt /home/spurs/dataset/rgbd_dataset_freiburg2_large_with_loop" output="screen" />
> 
> 改为：
> 
> <node pkg="orb_slam3" type="ros_rgbd_mapping" name="orb_slam3" args="$(find orb_slam3)/Examples/RGB-D/TUM2.yaml $(find orb_slam3)/Vocabulary/ORBvoc.txt /home/spurs/dataset/rgbd_dataset_freiburg2_large_with_loop" output="screen" output="log" launch-prefix="stterm -g 200x60 -e gdb -ex run --args" />
> ```
> 
> 以上调试orb_slam3这个节点

我试着运行这两行代码，然后获得了gdb调试界面如下：
![gdb调试截图1](https://github.com/lturing/ORB_SLAM3_ROS/assets/87161547/cadd7d5d-1f46-4a5e-95cd-8a8305c06bc6)
![gdb调试截图2](https://github.com/lturing/ORB_SLAM3_ROS/assets/87161547/facadf3f-3891-4dc5-9573-f9d410644f05)
很抱歉我没法复制它的内容，只能用这种特别费眼睛的方法截一张图上来，不过看这个反馈，我之前在另一个程序上好像也遇到过一次，也是一个稠密建图的程序，当时是遇到了core dump的问题，我用gdb查看core也是反馈这个名为liborb_slam3.so二进制文件的问题，然后我输入where就会弹出一堆类似的回馈. 我感觉这不是它们的问题

**Comment by lturing** [comment]
删掉所有CMakeLists.txt(项目下、Thirdparty下)文件中的 -march=native，重新运行build.sh，然后运行看看

**Comment by StevenLiuMC** [comment]
> 删掉所有CMakeLists.txt(项目下、Thirdparty下)文件中的 -march=native，重新运行build.sh，然后运行看看

哈哈哈还得是你啊作者,太强大了,问题解决了,非常感谢,就是march native的问题

**Comment by wfpurgator** [comment]
> 删掉所有CMakeLists.txt(项目下、Thirdparty下)文件中的 -march=native，重新运行build.sh，然后运行看看

可以，解决了  感谢作者。

**Comment by 29967** [comment]
我也报错这个，已经删除了march=native。完全没有头绪 ，虚拟机ubuntu20.06，分了32g运行内存，sudo make install 了pcl 1.13.0和pangolin v0.6，没有加参数。。。

**Comment by 29967** [comment]
ubuntu 20.04.06，写错了
