### ISSUE TITLE
运行自制TUM格式数据集稠密点云建图失败

### ISSUE THREAD

**Issue by StevenLiuMC** [lturing/ORB_SLAM3_ROS#8]
作者您好，之前很感谢您悉心的解答，但是今天我在自己尝试运行自制数据集时遇到了一个问题。具体问题如图所示：
![问题](https://github.com/lturing/ORB_SLAM3_ROS/assets/87161547/ca5c1911-ed3c-4bf6-a7be-54b5a5a981d4)
我是在室内空间使用Intel D435相机，在RealSense Viewer软件中录制的数据集，拥有RGB图像和深度图两组，图像像素为640*480，我在室内的运动范围虽然不大，但是也有大约4平米的空间。在这个自制数据集中我手持相机进行运动录制我们屋内的环境。但是这个RVIZ界面显示我的相机运动幅度非常小，通常运行TUM的fr1_room数据集时，中间的那个蓝绿红的方向标显得很小，因为背景就是fr1_room构建出来的正常稠密点云，但是今天我这个点云构建不知为啥不行，点云中的点都快赶上整个地图的大小了😂。所以想请教一下您，这种情况该如何解决，可能是相机配置文件yaml的问题吗（我使用的是D435相机的yaml文件）？还是说这是我录制的数据集的问题？

**Comment by StevenLiuMC** [comment]
> 作者您好，之前很感谢您悉心的解答，但是今天我在自己尝试运行自制数据集时遇到了一个问题。具体问题如图所示： ![问题](https://private-user-images.githubusercontent.com/87161547/331635006-ca5c1911-ed3c-4bf6-a7be-54b5a5a981d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTc4MTYsIm5iZiI6MTcxNTk1NzUxNiwicGF0aCI6Ii84NzE2MTU0Ny8zMzE2MzUwMDYtY2E1YzE5MTEtZWQzYy00YmY2LWE3YmUtNTRiNWE1YTk4MWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE0NTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MWVhMGVkY2NjNTE1MzllZDZiOWE0YzQzYjQyNzFjODAwNjE4ZjcwYzAyYzUzMTAxZDlhMWY3MzJkMjU1MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUQ8g-l2Xs68MUb2hAP7j6gPB0IG7pG75D6EvqZgsDo) 我是在室内空间使用Intel D435相机，在RealSense Viewer软件中录制的数据集，拥有RGB图像和深度图两组，图像像素为640*480，我在室内的运动范围虽然不大，但是也有大约4平米的空间。在这个自制数据集中我手持相机进行运动录制我们屋内的环境。但是这个RVIZ界面显示我的相机运动幅度非常小，通常运行TUM的fr1_room数据集时，中间的那个蓝绿红的方向标显得很小，因为背景就是fr1_room构建出来的正常稠密点云，但是今天我这个点云构建不知为啥不行，点云中的点都快赶上整个地图的大小了😂。所以想请教一下您，这种情况该如何解决，可能是相机配置文件yaml的问题吗（我使用的是D435相机的yaml文件）？还是说这是我录制的数据集的问题？

补充一个D345在realsense viewer里的使用设置：
![问题2](https://github.com/lturing/ORB_SLAM3_ROS/assets/87161547/b573c179-c156-4f00-a336-0e473c7121bb)
我顺便检查了一下D435相机的深度检测是否正确，看了下它在录制界面的深度基本没啥问题，不知道为啥稠密点云会建不起来

**Comment by StevenLiuMC** [comment]
再补充一个自制数据集点云建图，这个图建出来后看起来真的很好玩，感觉像是一个像素世界（点云的点太大了）
![问题点云](https://github.com/lturing/ORB_SLAM3_ROS/assets/87161547/1996937b-52ad-4a21-a69b-1b5a6fbacc00)

**Comment by lturing** [comment]
感觉是深度信息不对，检查一下[配置文件](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/Examples/RGB-D/RealSense_D435i.yaml#L38C1-L38C28)和[代码](https://github.com/lturing/ORB_SLAM3_ROS/blob/main/src/Tracking.cc#L1543)
