### ISSUE TITLE
没有报错，但是似乎只读取了图像而没进行任何处理

### ISSUE THREAD

**Issue by futingjun** [lturing/ORB_SLAM3_ROS#9]
作者您好，我想请问我在运行过程中将bag包路径改成我自己的路径后，rviz左侧能显示图像但是没有任何特征点的效果，右侧也没有显示点云，请问如何解决

**Comment by futingjun** [comment]
如果不使用bag包则报错
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.7.0) /home/asus/opencv3/modules/core/src/matrix_wrap.cpp:507: error: (-213:The function/feature is not implemented) Unknown/unsupported array type in function 'size'

**Comment by 1803170327** [comment]
我用作者提供的数据集，没有遇到这种问题，建议查一下associate.txt文件或者更换一下.yaml文件。但是我在使用自制TUM数据集的时候有类似情况，一般发生在画面比较单一的情况（例如对着一面白墙），除此之外在大多数情况下是可以提取到特征点的。此外，我没有对自己使用的相机进行标定，这应该会对特征提取有一些影响。

**Comment by futingjun** [comment]
> 我用作者提供的数据集，没有遇到这种问题，建议查一下associate.txt文件或者更换一下.yaml文件。但是我在使用自制TUM数据集的时候有类似情况，一般发生在画面比较单一的情况（例如对着一面白墙），除此之外在大多数情况下是可以提取到特征点的。此外，我没有对自己使用的相机进行标定，这应该会对特征提取有一些影响。

问题解决了，是我电脑里的opencv有冲突的问题，完全卸载后重新安装就好了
